#include "sg/dsl/Emit.hpp"

#include <charconv>
#include <map>
#include <set>
#include <sstream>

#include "sg/dsl/Kinds.hpp"

namespace sg::dsl {

namespace {

// A C++ string literal. Long ones are cut into pieces, which the compiler joins
// again: some compilers refuse a single literal past a few thousand characters.
std::string lit(const std::string& s) {
    std::string out;
    std::size_t in_piece = 0;
    out += '"';
    for (unsigned char c : s) {
        switch (c) {
            case '\\': out += "\\\\"; break;
            case '"': out += "\\\""; break;
            case '\n': out += "\\n\"\n        \""; in_piece = 0; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            default:
                if (c < 0x20) {
                    char buf[8];
                    std::snprintf(buf, sizeof buf, "\\%03o", c);
                    out += buf;
                } else {
                    out += static_cast<char>(c);
                }
        }
        if (++in_piece >= 2000 && c != '\n') {
            out += "\"\n        \"";
            in_piece = 0;
        }
    }
    out += '"';
    return out;
}

std::string lit(Key k) { return lit(k.str()); }

std::string number(double d) {
    char buf[40];
    const auto r = std::to_chars(buf, buf + sizeof buf, d);
    std::string s(buf, r.ptr);
    if (s.find_first_of(".en") == std::string::npos) s += ".0";
    return s;
}

std::string value(const Value& v) {
    if (const bool* b = std::get_if<bool>(&v)) return *b ? "true" : "false";
    if (const int64_t* i = std::get_if<int64_t>(&v)) return "int64_t{" + std::to_string(*i) + "}";
    if (const double* d = std::get_if<double>(&v)) return number(*d);
    if (const std::string* s = std::get_if<std::string>(&v)) return "std::string(" + lit(*s) + ")";
    return "sg::Value{}";
}

const char* keeps_name(Keeps k) {
    switch (k) {
        case Keeps::WhileActive: return "sg::Keeps::WhileActive";
        case Keeps::Always: return "sg::Keeps::Always";
        case Keeps::WhileShown: return "sg::Keeps::WhileShown";
        case Keeps::WhileFocused: return "sg::Keeps::WhileFocused";
        case Keeps::WhileEntered: return "sg::Keeps::WhileEntered";
    }
    return "sg::Keeps::WhileActive";
}

class Emitter {
public:
    Emitter(const Plan& p, const Kinds& k) : plan_(p), kinds_(k) {}

    std::string run(const std::string& name, const std::string& ns) {
        std::ostringstream o;
        o << "// Generated by sgc from";
        for (const std::string& f : plan_.sources) o << ' ' << f;
        o << ". Do not edit: the source is the source of truth.\n"
             "// Each line below is one call of the engine's own API, in the order the source declares them.\n"
             "#include \"sg/sg.hpp\"\n#include \"sg/domains/Atlas.hpp\"\n"
          << (guarded() ? "#include \"sg/dsl/Guard.hpp\"\n" : "")
          << "#include \"sg/dsl/Natives.hpp\"\n#include \"sg/dsl/Runtime.hpp\"\n\n"
             "namespace "
          << ns << " {\n\nvoid build_" << name
          << "(sg::StateGraph& graph, const sg::dsl::Natives& natives, sg::dsl::Bindings& bindings) {\n"
             "    (void)natives;\n    (void)bindings;\n";
        for (const Step& s : plan_.steps) std::visit([&](const auto& st) { step(o, st); }, s);
        o << "}\n\n}  // namespace " << ns << "\n";
        return o.str();
    }

private:
    const Plan& plan_;
    const Kinds& kinds_;
    std::map<std::string, std::string> vars_;
    std::map<std::string, std::string> fvars_;

    // Whether a transition of the plan is guarded: its guard is read back from its text.
    bool guarded() const {
        for (const Step& s : plan_.steps)
            if (const auto* c = std::get_if<plan::Connect>(&s))
                if (c->t.guard && !c->t.guard.text.empty()) return true;
        return false;
    }

    std::string& var(Key state) {
        auto it = vars_.find(state.str());
        if (it == vars_.end()) it = vars_.emplace(state.str(), "s" + std::to_string(vars_.size())).first;
        return it->second;
    }

    static const char* I() { return "    "; }

    void step(std::ostream& o, const plan::State& s) {
        const KindInfo* k = kinds_.find(s.kind);
        o << I() << "// state " << s.id.str() << " : " << s.kind << "\n";
        o << I() << "[[maybe_unused]] auto& " << var(s.id) << " = graph.add<" << (k ? k->cpp : "sg::State") << ">(" << lit(s.id) << ");\n";
    }
    void step(std::ostream& o, const plan::Extern& s) {
        o << I() << "// extern state " << s.id.str() << "\n";
        o << I() << "[[maybe_unused]] auto& " << var(s.id) << " = sg::dsl::expect_state(graph, " << lit(s.id) << ", " << lit(s.kind) << ");\n";
    }
    void step(std::ostream& o, const plan::Element& e) {
        if (e.own) o << I() << "sg::dsl::expect_element(" << var(e.state) << ", " << lit(e.id) << ", " << lit(e.kind) << ");\n";
        else o << I() << var(e.state) << ".add_element(" << lit(e.id) << ", " << lit(e.kind) << ");\n";
    }
    void step(std::ostream& o, const plan::Param& p) {
        if (!p.from_file.empty()) o << I() << "// " << p.key.str() << " from file(" << lit(p.from_file) << ")\n";
        if (p.element.empty()) o << I() << var(p.state) << ".params().set(" << lit(p.key) << ", " << value(p.value) << ");\n";
        else o << I() << var(p.state) << ".element(" << lit(p.element) << ").params.set(" << lit(p.key) << ", " << value(p.value) << ");\n";
    }

    void affine_lines(std::ostream& o, const Affine& a, const char* indent) {
        o << indent << "sg::Affine a;\n";
        if (a.copy_all) o << indent << "a.copy_all = true;\n";
        for (const Affine::Row& r : a.rows) {
            o << indent << "a.set(" << lit(r.param) << ", {";
            bool first = true;
            for (const Affine::Term& t : r.terms) {
                o << (first ? "" : ", ") << "sg::Affine::Term{" << lit(t.param) << ", " << number(t.k) << ", " << lit(t.arg) << ", "
                  << (t.of_target ? "true" : "false") << "}";
                first = false;
            }
            o << "}, " << number(r.bias) << ");\n";
        }
    }

    void step(std::ostream& o, const plan::Arrow& a) {
        const std::string& s = var(a.state);
        if (a.own) {
            o << I() << "sg::dsl::expect_arrow(" << s << ", " << lit(a.name) << ", " << lit(a.from) << ", " << lit(a.to) << ", " << lit(a.trigger) << ");\n";
            return;
        }
        const bool loop = a.to.empty();
        if (a.body == plan::Arrow::Body::Affine) {
            o << I() << "{\n";
            affine_lines(o, a.affine, "        ");
            o << "        " << s << ".affine(" << lit(a.name) << ", " << lit(a.from) << ", ";
            if (!loop) o << lit(a.to) << ", ";
            o << lit(a.trigger) << ", std::move(a));\n" << I() << "}\n";
            return;
        }
        const bool native = a.body == plan::Arrow::Body::Native;
        const std::string handler = (native ? "natives.arrow(" + lit(a.native) + ")" : std::string("nullptr")) + (native ? ", " + lit(a.native) : std::string());
        if (loop) o << I() << s << ".loop(" << lit(a.name) << ", " << lit(a.from) << ", " << lit(a.trigger) << ", " << handler << ");\n";
        else o << I() << s << ".arrow(" << lit(a.name) << ", " << lit(a.from) << ", " << lit(a.to) << ", " << lit(a.trigger) << ", " << handler << ");\n";
    }
    void step(std::ostream& o, const plan::Compose& c) {
        o << I() << var(c.state) << ".compose(" << lit(c.name) << ", " << lit(c.f) << ", " << lit(c.g) << ", " << lit(c.trigger) << ");\n";
    }
    void step(std::ostream& o, const plan::Says& s) { o << I() << var(s.state) << ".says(" << lit(s.event) << ");\n"; }

    void step(std::ostream& o, const plan::Functor& f) {
        if (f.built_elsewhere) {
            o << I() << "sg::dsl::expect_functor(graph, " << lit(f.name) << ", " << lit(f.from) << ", " << lit(f.to) << ");\n";
            return;
        }
        std::string v = "f" + std::to_string(fvars_.size());
        fvars_[f.name.str()] = v;
        o << I() << "// functor " << f.name.str() << " : " << f.from.str() << " -> " << f.to.str() << "\n";
        o << I() << "sg::Functor& " << v << " = graph.add_functor(" << lit(f.name) << ", " << lit(f.from) << ", " << lit(f.to) << ");\n";
    }
    void step(std::ostream& o, const plan::Object& ob) {
        const std::string& f = fvars_[ob.functor.str()];
        const std::string head = I() + f + ".on_object(" + lit(ob.src) + ", " + lit(ob.dst);
        switch (ob.transport) {
            case plan::Object::Transport::Copy: o << head << ");\n"; break;
            case plan::Object::Transport::Only: {
                o << head << ", sg::transport::only({";
                for (std::size_t i = 0; i < ob.names.size(); ++i) o << (i ? ", " : "") << lit(ob.names[i]);
                o << "}));\n";
                break;
            }
            case plan::Object::Transport::Swizzle: {
                o << head << ", sg::transport::swizzle({";
                for (std::size_t i = 0; i < ob.pairs.size(); ++i) o << (i ? ", " : "") << "{" << lit(ob.pairs[i].first) << ", " << lit(ob.pairs[i].second) << "}";
                o << "}, " << (ob.rest ? "true" : "false") << "));\n";
                break;
            }
            case plan::Object::Transport::Affine:
                o << I() << "{\n";
                affine_lines(o, ob.affine, "        ");
                o << "    " << head << ", sg::transport::affine(std::move(a)));\n" << I() << "}\n";
                break;
            case plan::Object::Transport::Native: o << head << ", natives.transport(" << lit(ob.native) << "), " << lit(ob.native) << ");\n"; break;
        }
    }
    void step(std::ostream& o, const plan::EventMap& m) {
        o << I() << fvars_[m.functor.str()] << ".on_event(" << lit(m.src) << ", " << lit(m.dst) << ");\n";
    }
    void step(std::ostream& o, const plan::ArrowMap& m) {
        o << I() << fvars_[m.functor.str()] << ".on_morphism(" << lit(m.src) << ", " << lit(m.dst) << ");\n";
    }
    void step(std::ostream& o, const plan::ComposeFunctors& c) {
        o << I() << "graph.compose_functors(" << lit(c.name) << ", {";
        for (std::size_t i = 0; i < c.chain.size(); ++i) o << (i ? ", " : "") << lit(c.chain[i]);
        o << "});\n";
    }
    void step(std::ostream& o, const plan::Lens& l) { o << I() << "graph.lens(" << lit(l.get) << ", " << lit(l.put) << ");\n"; }

    void step(std::ostream& o, const plan::Connect& c) {
        const sg::Transition& t = c.t;
        o << I() << "{\n        sg::Transition t;\n";
        o << "        t.from = " << lit(t.from) << ";\n";
        if (!t.to.empty()) o << "        t.to = " << lit(t.to) << ";\n";
        o << "        t.trigger = " << lit(t.trigger) << ";\n";
        if (t.kind == TransitionKind::Push) o << "        t.kind = sg::TransitionKind::Push;\n";
        if (t.kind == TransitionKind::Pop) o << "        t.kind = sg::TransitionKind::Pop;\n";
        if (!t.functor.empty()) o << "        t.functor = " << lit(t.functor) << ";\n";
        if (!t.name.empty()) o << "        t.name = " << lit(t.name) << ";\n";
        for (const auto& kv : t.enter) o << "        t.enter.set(" << lit(kv.first) << ", " << value(kv.second) << ");\n";
        if (t.guard && !t.guard.text.empty()) o << "        t.guard = sg::dsl::guard(" << lit(t.guard.text) << ");\n";
        o << "        graph.connect(std::move(t));\n" << I() << "}\n";
    }
    void step(std::ostream& o, const plan::Embed& em) {
        const sg::Embedding& e = em.e;
        o << I() << "{\n        sg::Embedding e;\n";
        o << "        e.name = " << lit(e.name) << ";\n        e.host = " << lit(e.host) << ";\n        e.portal = " << lit(e.portal)
          << ";\n        e.guest = " << lit(e.guest) << ";\n";
        if (!e.subject.empty()) o << "        e.subject = " << lit(e.subject) << ";\n";
        if (!e.in.empty()) o << "        e.in = " << lit(e.in) << ";\n";
        if (!e.out.empty()) o << "        e.out = " << lit(e.out) << ";\n";
        if (e.sync != EmbedSync::Commit) o << "        e.sync = sg::EmbedSync::" << (e.sync == EmbedSync::Live ? "Live" : "View") << ";\n";
        if (e.propagate != Propagation::OnChange) {
            const char* p = e.propagate == Propagation::Continuous ? "Continuous" : e.propagate == Propagation::OnEvent ? "OnEvent" : "Manual";
            o << "        e.propagate = sg::Propagation::" << p << ";\n";
        }
        if (!e.focus) o << "        e.focus = false;\n";
        if (e.follows) o << "        e.follows = true;\n";
        if (e.recurses) o << "        e.recurses = true;\n";
        o << "        graph.embed(std::move(e));\n" << I() << "}\n";
    }
    void step(std::ostream& o, const plan::Glue& g) {
        o << I() << "sg::glue_doorway(graph, " << lit(g.name) << ", " << lit(g.a) << ", " << lit(g.pa) << ", " << lit(g.b) << ", " << lit(g.pb);
        if (!g.also.empty()) {
            o << ", {";
            for (std::size_t i = 0; i < g.also.size(); ++i) o << (i ? ", " : "") << "{" << lit(g.also[i].first) << ", " << lit(g.also[i].second) << "}";
            o << "}";
        }
        if (g.wraps) o << (g.also.empty() ? ", {}" : "") << ", true";
        o << ");\n";
    }
    void step(std::ostream& o, const plan::Drive& d) {
        o << I() << "sg::drive(graph, sg::dsl::clock(graph, " << lit(d.d.clock) << "), " << lit(d.d.state) << ", " << lit(d.d.trigger) << ", "
          << (d.d.additive ? "true" : "false") << ", " << keeps_name(d.d.keeps) << ");\n";
    }
    void step(std::ostream& o, const plan::Port& p) { o << I() << "graph.port(" << lit(p.state) << ", " << lit(p.event) << ");\n"; }
    void step(std::ostream& o, const plan::Keep& k) { o << I() << "graph.keep(" << lit(k.functor) << ");\n"; }
    void step(std::ostream& o, const plan::Wear& w) { o << I() << "sg::wear(graph, " << lit(w.host) << ", " << lit(w.look) << ");\n"; }
    void step(std::ostream& o, const plan::Film& f) {
        o << I() << "sg::film(graph, " << lit(f.camera) << ", " << lit(f.world);
        if (!f.rig.empty()) o << ", " << lit(f.rig);
        o << ");\n";
    }
    void step(std::ostream& o, const plan::Initial& i) { o << I() << "graph.set_initial(" << lit(i.state) << ");\n"; }
    void step(std::ostream& o, const plan::Edit& e) {
        o << I() << "{\n        sg::Edit e;\n        e.state = " << lit(e.state) << ";\n        e.event = " << lit(e.event)
          << ";\n        e.reply = " << lit(e.reply) << ";\n        e.apply = natives.edit(" << lit(e.native) << ");\n        e.native = " << lit(e.native) << ";\n        graph.edit(std::move(e));\n"
          << I() << "}\n";
    }
    void step(std::ostream& o, const plan::Bind& b) {
        o << I() << "// bind " << b.device << "\n";
        for (const plan::Bind::Entry& e : b.entries) {
            o << I() << "bindings.add(" << lit(b.device) << ", " << lit(e.key) << ", " << lit(e.event);
            if (!e.args.empty()) {
                o << ", sg::Params{}";
                for (const auto& kv : e.args) o << ".set(" << lit(kv.first) << ", " << value(kv.second) << ")";
            }
            o << ");\n";
        }
    }
};

}  // namespace

std::string emit_cpp(const Plan& plan, const std::string& name, const std::string& ns) {
    return Emitter(plan, Kinds::standard()).run(name, ns);
}

}  // namespace sg::dsl
