# SPIR-V into a header: its words, as the shader module takes them.
file(READ ${IN} hex HEX)
string(LENGTH "${hex}" n)
math(EXPR words "${n} / 8")
set(body "")
set(i 0)
while(i LESS words)
  math(EXPR at "${i} * 8")
  string(SUBSTRING "${hex}" ${at} 8 w)
  # Little-endian bytes: b0 b1 b2 b3 -> 0xb3b2b1b0.
  string(SUBSTRING "${w}" 0 2 b0)
  string(SUBSTRING "${w}" 2 2 b1)
  string(SUBSTRING "${w}" 4 2 b2)
  string(SUBSTRING "${w}" 6 2 b3)
  string(APPEND body "0x${b3}${b2}${b1}${b0}u,")
  math(EXPR i "${i} + 1")
  math(EXPR col "${i} % 8")
  if(col EQUAL 0)
    string(APPEND body "\n")
  endif()
endwhile()
math(EXPR bytes "${words} * 4")
file(WRITE ${OUT} "// Built from src/gpu/algebra.comp: do not edit.\n#pragma once\n#include <cstddef>\n#include <cstdint>\nstatic const uint32_t sg_algebra_spv[] = {\n${body}};\nstatic const size_t sg_algebra_spv_size = ${bytes};\n")
