# Optional mature Internet data plane, isolated from stategine::net/core.
option(SG_NET_ICE "Build the libdatachannel ICE/DTLS/SCTP transport" OFF)
option(SG_NET_ICE_FETCH "Fetch pinned libdatachannel and Mbed TLS when ICE is enabled" ON)
function(stategine_network_ice)
  if(NOT SG_NET_ICE)
    return()
  endif()
  # Repeated native release/debug teardown tests reproduce a freed SCTP
  # socket being used by a queued shared-owner task with MinGW GCC 16/UCRT.
  # Clang/libc++ and Linux GCC pass the same tests. Do not ship the crashing
  # configuration or conceal it by omitting the teardown/reconnection tests.
  if(WIN32 AND CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND
     CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 16 AND
     CMAKE_CXX_COMPILER_VERSION VERSION_LESS 17)
    message(FATAL_ERROR "SG_NET_ICE: MinGW GCC 16/UCRT has a reproduced RTC teardown use-after-free. Use a Clang/libc++ build for ICE, or SG_NET_ICE=OFF for the unchanged CPU/CUDA and UDP targets.")
  endif()
  if(SG_NET_ICE_FETCH)
    if(MSVC)
      message(FATAL_ERROR "SG_NET_ICE_FETCH uses threaded Mbed TLS with pthreads. For MSVC, install native LibDataChannel and configure SG_NET_ICE_FETCH=OFF.")
    endif()
    include(FetchContent)
    set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
    set(ENABLE_PROGRAMS OFF)
    set(ENABLE_TESTING OFF)
    set(BUILD_SHARED_LIBS OFF)
    FetchContent_Declare(sg_ice_tls
      GIT_REPOSITORY https://github.com/Mbed-TLS/mbedtls.git
      GIT_TAG 068ff080b369adfac81509f9b57b2afabaf82dc5)
    FetchContent_MakeAvailable(sg_ice_tls)
    find_package(Threads REQUIRED)
    foreach(_target mbedtls mbedx509 mbedcrypto)
      target_compile_definitions(${_target} PUBLIC MBEDTLS_USER_CONFIG_FILE="${CMAKE_CURRENT_SOURCE_DIR}/cmake/ice_mbedtls_config.h")
      target_link_libraries(${_target} PUBLIC Threads::Threads)
    endforeach()
    add_library(MbedTLS::MbedTLS INTERFACE IMPORTED GLOBAL)
    set_target_properties(MbedTLS::MbedTLS PROPERTIES INTERFACE_LINK_LIBRARIES "mbedtls;mbedx509;mbedcrypto")
    set(USE_MBEDTLS ON)
    set(NO_MEDIA ON)
    set(NO_WEBSOCKET OFF)
    set(NO_TESTS ON)
    set(NO_EXAMPLES ON)
    FetchContent_Declare(sg_ice
      GIT_REPOSITORY https://github.com/paullouisageneau/libdatachannel.git
      GIT_TAG 6b1e2e620f1e37f0eafeee702eaea0043cb305fd)
    FetchContent_GetProperties(sg_ice)
    if(NOT sg_ice_POPULATED)
      FetchContent_Populate(sg_ice)
      execute_process(COMMAND ${CMAKE_COMMAND} -DSOURCE_DIR=${sg_ice_SOURCE_DIR}
        -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/patch_ice.cmake COMMAND_ERROR_IS_FATAL ANY)
      add_subdirectory(${sg_ice_SOURCE_DIR} ${sg_ice_BINARY_DIR})
    endif()
  else()
    find_package(LibDataChannel 0.24 CONFIG REQUIRED)
  endif()
  add_library(stategine_net_ice STATIC src/net/IceTransport.cpp)
  add_library(stategine::net_ice ALIAS stategine_net_ice)
  target_link_libraries(stategine_net_ice PUBLIC stategine_net PRIVATE LibDataChannel::LibDataChannel)
  target_link_libraries(stategine_net_ice PRIVATE stategine_warnings)
  foreach(_example sg_net_pong sg_net_verified_peer)
    if(TARGET ${_example})
      target_compile_definitions(${_example} PRIVATE SG_EXAMPLE_ICE)
      target_link_libraries(${_example} PRIVATE stategine_net_ice LibDataChannel::LibDataChannel)
    endif()
  endforeach()
  if(SG_BUILD_TESTS)
    add_executable(sg_net_ice tests/test_net_ice.cpp)
    target_link_libraries(sg_net_ice PRIVATE stategine_net_ice stategine_static_runtime)
    if(TARGET stategine_dsl)
      target_link_libraries(sg_net_ice PRIVATE stategine_dsl)
      target_compile_definitions(sg_net_ice PRIVATE SG_TEST_WORLD)
      stategine_compile_dsl(sg_net_ice NAME verified SOURCES examples/verified.sg)
    endif()
    if(TARGET juice-static)
      target_sources(sg_net_ice PRIVATE tests/IceFaults.cpp)
      target_link_libraries(sg_net_ice PRIVATE juice-static)
      target_compile_definitions(sg_net_ice PRIVATE SG_TEST_TURN)
    elseif(TARGET juice)
      target_sources(sg_net_ice PRIVATE tests/IceFaults.cpp)
      target_link_libraries(sg_net_ice PRIVATE juice)
      target_compile_definitions(sg_net_ice PRIVATE SG_TEST_TURN)
    endif()
    add_test(NAME sg_net_ice COMMAND sg_net_ice)
    set_tests_properties(sg_net_ice PROPERTIES TIMEOUT 120)
    if(Python3_Interpreter_FOUND AND TARGET sg_net_verified_peer AND TARGET sg_net_pong)
      execute_process(COMMAND ${Python3_EXECUTABLE} -c "import websockets.legacy.server"
        RESULT_VARIABLE _websockets OUTPUT_QUIET ERROR_QUIET)
      find_program(SG_NET_TEST_OPENSSL openssl HINTS "$ENV{ProgramFiles}/Git/usr/bin")
      if(_websockets EQUAL 0 AND SG_NET_TEST_OPENSSL)
        add_test(NAME sg_net_ice_processes COMMAND ${Python3_EXECUTABLE}
          ${CMAKE_CURRENT_SOURCE_DIR}/tests/net_ice_processes.py
          $<TARGET_FILE:sg_net_verified_peer> $<TARGET_FILE:sg_net_keys> $<TARGET_FILE:sg_net_pong>
          ${CMAKE_CURRENT_SOURCE_DIR}/examples/ice_rendezvous.py ${SG_NET_TEST_OPENSSL}
          ${CMAKE_CURRENT_BINARY_DIR}/out/network/ice-processes)
        set_tests_properties(sg_net_ice_processes PROPERTIES TIMEOUT 180)
      else()
        message(STATUS "stategine: WSS process test requires Python websockets and openssl; ICE C++ tests remain enabled")
      endif()
    endif()
  endif()
endfunction()
stategine_network_ice()
