# libdatachannel 0.24.6 replaces the buffered-amount callback from teardown
# while send workers use it under mSendMutex. Protect replacement with the
# same (upstream recursive) mutex. This changes no wire/protocol behavior.
set(_file "${SOURCE_DIR}/src/impl/sctptransport.cpp")
file(READ "${_file}" _source)
set(_old "void SctpTransport::onBufferedAmount(amount_callback callback) {\n\tmBufferedAmountCallback = std::move(callback);\n}")
set(_new "void SctpTransport::onBufferedAmount(amount_callback callback) {\n\tstd::lock_guard lock(mSendMutex);\n\tmBufferedAmountCallback = std::move(callback);\n}")
string(FIND "${_source}" "${_new}" _patched)
if(_patched LESS 0)
  string(FIND "${_source}" "${_old}" _found)
  if(_found LESS 0)
    message(FATAL_ERROR "Pinned libdatachannel callback no longer matches; review its teardown synchronization")
  endif()
  string(REPLACE "${_old}" "${_new}" _source "${_source}")
  file(WRITE "${_file}" "${_source}")
endif()

# A physical lane has one data channel. Four maximum-sized messages bound
# the vendor receive queue to 16 MiB at our default 4 MiB message limit.
# Polling the application queue supplies backpressure; close must wake a
# vendor worker blocked on this queue. Neither change alters the wire.
set(_file "${SOURCE_DIR}/src/impl/datachannel.cpp")
file(READ "${_file}" _source)
set(_before "${_source}")
set(_old "mRecvQueue(RECV_QUEUE_LIMIT, message_size_func)")
set(_new "mRecvQueue(4, message_size_func)")
string(FIND "${_source}" "${_new}" _patched)
if(_patched LESS 0)
  string(FIND "${_source}" "${_old}" _found)
  if(_found LESS 0)
    message(FATAL_ERROR "Pinned libdatachannel receive queue no longer matches")
  endif()
  string(REPLACE "${_old}" "${_new}" _source "${_source}")
endif()
set(_old "void DataChannel::close() {\n\tPLOG_VERBOSE << \"Closing DataChannel\";")
set(_new "void DataChannel::close() {\n\tPLOG_VERBOSE << \"Closing DataChannel\";\n\tmRecvQueue.stop();")
string(FIND "${_source}" "${_new}" _patched)
if(_patched LESS 0)
  string(FIND "${_source}" "${_old}" _found)
  if(_found LESS 0)
    message(FATAL_ERROR "Pinned libdatachannel channel close no longer matches")
  endif()
  string(REPLACE "${_old}" "${_new}" _source "${_source}")
endif()
if(NOT "${_source}" STREQUAL "${_before}")
  file(WRITE "${_file}" "${_source}")
endif()

# configuration.cpp uses transform; libc++ does not supply <algorithm>
# indirectly through <regex>. Keep the pinned build portable.
set(_file "${SOURCE_DIR}/src/configuration.cpp")
file(READ "${_file}" _source)
string(FIND "${_source}" "#include <algorithm>" _patched)
if(_patched LESS 0)
  string(REPLACE "#include <regex>" "#include <algorithm>\n#include <regex>" _source "${_source}")
  file(WRITE "${_file}" "${_source}")
endif()

# Retire raw usrsctp callback access before freeing its socket. Its callbacks
# acquire Instances' shared lock; erase waits for those users and prevents a
# later upcall from touching a socket already released by usrsctp_close().
set(_file "${SOURCE_DIR}/src/impl/sctptransport.cpp")
file(READ "${_file}" _source)
set(_old "SctpTransport::~SctpTransport() {\n\tPLOG_DEBUG << \"Destroying SCTP transport\";")
set(_new "SctpTransport::~SctpTransport() {\n\tPLOG_DEBUG << \"Destroying SCTP transport\";\n\tInstances->erase(this);")
string(FIND "${_source}" "${_new}" _patched)
if(_patched LESS 0)
  string(FIND "${_source}" "${_old}" _found)
  if(_found LESS 0)
    message(FATAL_ERROR "Pinned libdatachannel SCTP destructor no longer matches")
  endif()
  string(REPLACE "${_old}" "${_new}" _source "${_source}")
  string(REPLACE "\tusrsctp_deregister_address(this);\n\tInstances->erase(this);" "\tusrsctp_deregister_address(this);" _source "${_source}")
  file(WRITE "${_file}" "${_source}")
endif()

# The description IO thread and DTLS Connected callback can both initialize
# SCTP. Match the existing DTLS initialization guard so only one association
# can register its receive callback on a given DTLS transport.
set(_file "${SOURCE_DIR}/src/impl/peerconnection.hpp")
file(READ "${_file}" _source)
set(_old "shared_ptr<SctpTransport> mSctpTransport;")
set(_new "shared_ptr<SctpTransport> mSctpTransport;\n\tstd::mutex mSctpTransportInitMutex;")
string(FIND "${_source}" "${_new}" _patched)
if(_patched LESS 0)
  string(FIND "${_source}" "${_old}" _found)
  if(_found LESS 0)
    message(FATAL_ERROR "Pinned libdatachannel SCTP member no longer matches")
  endif()
  string(REPLACE "${_old}" "${_new}" _source "${_source}")
  file(WRITE "${_file}" "${_source}")
endif()
set(_file "${SOURCE_DIR}/src/impl/peerconnection.cpp")
file(READ "${_file}" _source)
set(_old "shared_ptr<SctpTransport> PeerConnection::initSctpTransport() {\n\ttry {")
set(_new "shared_ptr<SctpTransport> PeerConnection::initSctpTransport() {\n\tstd::lock_guard lock(mSctpTransportInitMutex);\n\ttry {")
string(FIND "${_source}" "${_new}" _patched)
if(_patched LESS 0)
  string(FIND "${_source}" "${_old}" _found)
  if(_found LESS 0)
    message(FATAL_ERROR "Pinned libdatachannel SCTP initializer no longer matches")
  endif()
  string(REPLACE "${_old}" "${_new}" _source "${_source}")
  file(WRITE "${_file}" "${_source}")
endif()
