# Browser executors are optional dependants, never dependencies of the world.
option(SG_BUILD_WEB "Build browser platform adapters" ${EMSCRIPTEN})
set(SG_BROWSER_NATIVE_DIR "" CACHE PATH "Native build for real browser interoperability tests")
set(SG_BROWSER_ICE_DIR "" CACHE PATH "Native libdatachannel build for browser interoperability")
set(SG_BROWSER_EXECUTABLE "" CACHE FILEPATH "Chromium/Edge executable for real WebGPU tests")
set(SG_BROWSER_NODE "node" CACHE FILEPATH "Node executable for native/Wasm comparison")
if(EMSCRIPTEN AND SG_BUILD_TESTS AND SG_BROWSER_NATIVE_DIR AND SG_BROWSER_ICE_DIR AND SG_BROWSER_EXECUTABLE)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  add_test(NAME sg_browser_integration COMMAND ${Python3_EXECUTABLE}
    "${CMAKE_CURRENT_SOURCE_DIR}/tests/browser.py" --native "${SG_BROWSER_NATIVE_DIR}"
    --wasm "${CMAKE_CURRENT_BINARY_DIR}" --ice-build "${SG_BROWSER_ICE_DIR}"
    --browser "${SG_BROWSER_EXECUTABLE}" --node "${SG_BROWSER_NODE}")
  set_tests_properties(sg_browser_integration PROPERTIES TIMEOUT 240 RUN_SERIAL TRUE)
endif()
if(SG_BUILD_TESTS)
  add_executable(sg_view_plan tests/test_view_plan.cpp)
  target_link_libraries(sg_view_plan PRIVATE stategine_render stategine_dsl)
  stategine_compile_dsl(sg_view_plan NAME view_plan SOURCES tests/dsl/view_plan.sg)
  add_test(NAME sg_view_plan COMMAND sg_view_plan)
  add_executable(sg_cross_platform tests/test_cross_platform.cpp)
  target_link_libraries(sg_cross_platform PRIVATE stategine_render stategine_net stategine_dsl)
  stategine_compile_dsl(sg_cross_platform NAME view_plan SOURCES tests/dsl/view_plan.sg)
  add_test(NAME sg_cross_platform COMMAND sg_cross_platform)
  if(TARGET glfw AND TARGET stategine_gl)
    add_executable(sg_browser_render tests/browser_render.cpp)
    target_link_libraries(sg_browser_render PRIVATE stategine_gl stategine_dsl stategine_net stategine_static_runtime glfw)
    if(WIN32)
      target_link_libraries(sg_browser_render PRIVATE opengl32)
    endif()
    stategine_compile_dsl(sg_browser_render NAME browser_render SOURCES tests/dsl/browser_render.sg)
    add_test(NAME sg_browser_render COMMAND sg_browser_render)
  endif()
endif()
if(NOT EMSCRIPTEN OR NOT SG_BUILD_WEB)
  return()
endif()
add_library(stategine_web STATIC src/web/WebRtc.cpp src/web/Input.cpp src/web/WebGPU.cpp)
add_library(stategine::web ALIAS stategine_web)
target_link_libraries(stategine_web PUBLIC stategine_render stategine_net stategine_dsl)
target_link_options(stategine_web INTERFACE --bind
  "--pre-js=${CMAKE_CURRENT_SOURCE_DIR}/src/web/rtc.js"
  "--pre-js=${CMAKE_CURRENT_SOURCE_DIR}/src/web/input.js"
  "--pre-js=${CMAKE_CURRENT_SOURCE_DIR}/src/web/shaders.js"
  "--pre-js=${CMAKE_CURRENT_SOURCE_DIR}/src/web/gpu.js")
set_property(TARGET stategine_web PROPERTY INTERFACE_LINK_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/src/web/rtc.js;${CMAKE_CURRENT_SOURCE_DIR}/src/web/input.js;${CMAKE_CURRENT_SOURCE_DIR}/src/web/shaders.js;${CMAKE_CURRENT_SOURCE_DIR}/src/web/gpu.js")
if(SG_BUILD_EXAMPLES OR SG_BUILD_TESTS)
  add_executable(sg_browser examples/browser/main.cpp examples/pong/Pong.cpp examples/pong/Motion.cpp examples/pong/Secure.cpp examples/Signed.cpp examples/IceSignals.cpp)
  target_link_libraries(sg_browser PRIVATE stategine_web)
  if(SG_BUILD_TESTS)
    target_compile_definitions(sg_browser PRIVATE SG_WEB_TESTS)
  endif()
  stategine_compile_dsl(sg_browser NAME pong SOURCES examples/pong/pong.sg)
  target_link_options(sg_browser PRIVATE -sMODULARIZE=1 -sEXPORT_NAME=createStategine -sNO_EXIT_RUNTIME=1 -sSTACK_SIZE=1048576 "-sEXPORTED_RUNTIME_METHODS=['ccall','FS']" "--pre-js=${CMAKE_CURRENT_SOURCE_DIR}/examples/browser/platform.js")
  configure_file(examples/browser/index.html "${CMAKE_CURRENT_BINARY_DIR}/index.html" COPYONLY)
  set_property(TARGET sg_browser APPEND PROPERTY LINK_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/examples/browser/platform.js")
endif()
if(SG_BUILD_TESTS)
  add_executable(sg_browser_render tests/browser_render.cpp)
  target_link_libraries(sg_browser_render PRIVATE stategine_web)
  stategine_compile_dsl(sg_browser_render NAME browser_render SOURCES tests/dsl/browser_render.sg)
  target_link_options(sg_browser_render PRIVATE -sMODULARIZE=1 -sEXPORT_NAME=createRender -sNO_EXIT_RUNTIME=1 -sSTACK_SIZE=1048576 "-sEXPORTED_RUNTIME_METHODS=['ccall']")
  configure_file(tests/browser_render.html "${CMAKE_CURRENT_BINARY_DIR}/render.html" COPYONLY)
endif()
